POST http://localhost:7071/runtime/webhooks/eventgrid?functionName=ProcessBlob HTTP/1.1
Content-Type: application/json
aeg-event-type: Notification

[{
  "topic": "/subscriptions/4fbbab4a-92f8-41b0-bd1c-44dee8cd6483/resourceGroups/rg-anmock/providers/Microsoft.Storage/storageAccounts/team9anmockaccount",
  "subject": "/blobServices/default/containers/batchfiles/blobs/4711-testdata.txt",
  "eventType": "Microsoft.Storage.BlobCreated",
  "id": "1ded67bf-801e-0029-6edb-0d9cd2065527",
  "data": {
    "api": "PutBlob",
    "clientRequestId": "6ad379bf-6e30-47dd-a24e-8bca16aa40d8",
    "requestId": "1ded67bf-801e-0029-6edb-0d9cd2000000",
    "eTag": "0x8D9DBF2E2D36965",
    "contentType": "text/plain",
    "contentLength": 184458,
    "blobType": "BlockBlob",
    "url": "https://team9anmockaccount.blob.core.windows.net/batchfiles/4711-testdata.txt",
    "sequencer": "000000000000000000000000000007A80000000000000d82",
    "storageDiagnostics": {
      "batchId": "517a61c6-9006-0014-00db-0d29f4000000"
    }
  },
  "dataVersion": "",
  "metadataVersion": "1",
  "eventTime": "2022-01-20T08:57:28.3730299Z"
}]