name: Build and deploy

on:
  push:
    paths-ignore:
    - 'README.md'
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  FUNCTIONAPP_PACKAGE_PATH: 'IcecreamRatings'
  DOTNET_VERSION: '3.1.415'   

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ env.FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ secrets.FUNCTIONAPP_NAME }}
        package: '${{ env.FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.FUNCTIONAPP_PUBLISH_PROFILE }}